paths:
  output_dir: '/local2/fredxu/FD-Bench/exps'  #* your path to save exp log and ckpt
  report_to: wandb   #* choices: ['wandb', 'tensorboard', 'all']
  tensorboard_dir: '/local2/fredxu/FD-Bench/runs/' #* path to save logs, if `report_to=tensorboard`

training:
  batch_size: 128
  epochs: 800
  resume_step: 0
  checkpointing_steps: 100
  eval_steps: 20
  start_epoch: 0
  seed: 42
  num_workers: 4
  pin_mem: true

model:
  spa_mod: 'fourier'  
  tem_mod: 'next_step'      
  pred_tgt: 'variable'
  drop: 0.0
  drop_path: 0.1
  
  modes1: 48
  modes2: 48
  width: 64
  
  fno_bias: false
  fno_blocks: 1
  fno_softshrink: 0.00
  double_skip: false
  hidden_size: 512
  num_layers: 12
  checkpoint_activations: false
  ls_w: 4
  ls_dp_rank: 16

data:
  PDE_type: 'SPDE' 
  data_path: '/local2/fredxu/FD-Bench/NS_u0_xi_nu4'                  #* your path to data
  data_set: '0.mat' 
  input_size: 128
  in_chans: 1
  reduced_resolution: 1
  reduced_resolution_t: 1 
  reduced_batch: 1
  initial_step: 1

  # PDE_type: 'Well'
  # well_dataset_name: "shear_flow"
  # data_path: '/wanghaixin/well/datasets/'
  # data_set: 'shear_flow_Reynolds_1e5_Schmidt_1e1.hdf5'
  # input_size: 128
  # in_chans: 4
  # reduced_resolution: 2

  # PDE_type: 'KF'
  # data_path: '/wanghaixin/FNS-KF/'
  # data_set: 'FNS-KF.nc'
  # num_trajectories: -1
  # max_trajectories: 1000
  # max_num_time_steps: 3
  # input_size: 128
  # in_chans: 5
  # reduced_resolution: 1
  
optimizer:
  opt: 'adamw'
  opt_eps: 1.0e-8
  opt_betas: null
  clip_grad: 1
  momentum: 0.9
  weight_decay: 0.05
  adam_beta1: 0.9
  adam_beta2: 0.999 
  adam_weight_decay: 0
  adam_epsilon: 1.0e-8


lr_scheduler:
  # scheduler: 'CosineAnnealing'
  scheduler: 'lambda'
  step_size_up: 1000
  step_size_down: 1000
  lr: 1.0e-3
  lr_noise: null
  lr_noise_pct: 0.67
  lr_noise_std: 1.0
  warmup_lr: 1.0e-3
  min_lr: 5.0e-4
  decay_epochs: 30
  warmup_epochs: 5
  cooldown_epochs: 10
  patience_epochs: 10
  decay_rate: 0.1

distribution:
  gradient_accumulation_steps: 1
  allow_tf32: True
  mixed_precision: "no"
