paths:
  output_dir: '/wanghaixin/FD-Bench/exps'  #* your path to save exp log and ckpt
  tensorboard_dir: '/wanghaixin/FD-Bench/runs/' #* path to save logs, if `report_to=tensorboard`

data:
  tem_mod: 'next_step' 
  batch_size: 4
  num_workers: 0
  
  # PDE_type: 'CNS'      #* choices: ['CNS']
  # data_path: '/wanghaixin/PDEBench/data/2D/CFD/2D_Train_Rand/'                  #* your path to data
  # data_set: '2D_CFD_Rand_M0.1_Eta1e-08_Zeta1e-08_periodic_512_Train.hdf5'       #* file_name
  # input_size: 128 
  # in_chans: 4 
  # reduced_resolution: 4

  # PDE_type: 'DR'
  # data_path: '/wanghaixin/PDEBench/data/2D/diffusion-reaction/'
  # data_set: '2D_diff-react_NA_NA.h5'
  # input_size: 128
  # in_chans: 2
  # reduced_resolution: 1

  PDE_type: 'KF'
  data_path: '/wanghaixin/FNS-KF/'
  data_set: 'FNS-KF.nc'
  num_trajectories: -1
  max_trajectories: 1000
  max_num_time_steps: 3
  input_size: 128
  in_chans: 5
  reduced_resolution: 1

  reduced_resolution_t: 1 
  reduced_batch: 1
  initial_step: 1


