paths:
  output_dir: '../ckpt'  #* your path to save ckpt
  tensorboard_dir: '/home/whx/FD-Bench/runs/' #* your path to save logs
  autoresume: false
  resume: false

training:
  batch_size: 16
  epochs: 100
  start_epoch: 0
  eval: false
  use_amp: true
  dist_eval: true
  device: 'cuda'
  seed: 0
  num_workers: 4
  pin_mem: true

model:
  spa_mod: 'self_atten'  #* choices: ['self_atten', 'fourier', 'graph']
  tem_mod: 'next_step'      #* choices: ['linear', ]
  drop: 0.0
  drop_path: 0.1
  model_ema: false
  model_ema_decay: 0.99996
  model_ema_force_cpu: false
  
  # Self-atten
  arch: 'deit_small'
  patch_size: 4
  num_attention_heads: 1
  mixing_type: 'afno'  # choices: ['afno', 'sa', 'ls', 'gfn', 'bfno']
  
  fno_bias: false
  fno_blocks: 1
  fno_softshrink: 0.00
  double_skip: false
  hidden_size: 256
  num_layers: 12
  checkpoint_activations: false
  ls_w: 4
  ls_dp_rank: 16

data:
  PDE_type: 'CNS'      #* choices: ['CNS']
  data_path: '/local2/shared_data/DBench_data/PDEBench/'                  #* your path to data
  data_set: '2D_CFD_Turb_M0.1_Eta1e-08_Zeta1e-08_periodic_512_Train.hdf5' #* file_name
  input_size: 128  
  in_chans: 4
  finetune: ''
  reduced_resolution: 4
  reduced_resolution_t: 1 
  reduced_batch: 1
  initial_step: 10

optimizer:
  opt: 'adamw'
  opt_eps: 1.0e-8
  opt_betas: null
  clip_grad: 1
  momentum: 0.9
  weight_decay: 0.05


lr_scheduler:
  sched: 'cosine'
  lr: 5.0e-4
  lr_noise: null
  lr_noise_pct: 0.67
  lr_noise_std: 1.0
  warmup_lr: 1.0e-6
  min_lr: 1.0e-5
  decay_epochs: 30
  warmup_epochs: 5
  cooldown_epochs: 10
  patience_epochs: 10
  decay_rate: 0.1


augmentation:
  color_jitter: 0.4
  aa: 'rand-m9-mstd0.5-inc1'
  smoothing: 0.1
  train_interpolation: 'bicubic'
  repeated_aug: false
  
  # Random Erase
  reprob: 0
  remode: 'pixel'
  recount: 1
  resplit: false
  
  # Mixup
  mixup: 0.8
  cutmix: 1.0
  cutmix_minmax: null
  mixup_prob: 1.0
  mixup_switch_prob: 0.5
  mixup_mode: 'batch'

distributed:
  world_size: 1
  dist_url: 'env://'
